# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Run inference using a previously saved offload profile.

Loads the profile generated by ``run_profile.py`` so the model jumps straight
to optimized inference without repeating discovery or profiling.

Usage:
    python run_infer.py --prompt "A fox riding a bicycle through a meadow" [--profile-dir ./wan_profile]
"""

import argparse

import torch
from diffusers import WanPipeline
from diffusers.utils import export_to_video

import flextensor
from flextensor import OffloadConfig

MODEL_ID = "Wan-AI/Wan2.2-T2V-A14B-Diffusers"
MODULE_PATTERNS = [
    "rope",
    "patch_embedding",
    "condition_embedder",
    "blocks.*",
    "norm_out",
    "proj_out",
]

DEFAULT_PROMPT = (
    "A penguin and a rabbit painting a canvas together in a sunny art studio. "
    "The penguin holds a palette of bright colors, while the rabbit carefully "
    "applies brushstrokes with a tiny brush. Paint splatters cover the wooden "
    "floor and their aprons."
)
DEFAULT_NEGATIVE_PROMPT = (
    "blurry, low resolution, oversaturated, underexposed, distorted anatomy, "
    "extra limbs, missing fingers, poorly drawn face, watermark, text overlay, "
    "static image, grainy, noisy background"
)


def main():
    parser = argparse.ArgumentParser(description="Wan2.2 inference with a saved FlexTensor profile")
    parser.add_argument("--prompt", default=DEFAULT_PROMPT, help="Text prompt for video generation")
    parser.add_argument("--negative-prompt", default=DEFAULT_NEGATIVE_PROMPT, help="Negative prompt")
    parser.add_argument("--num-frames", type=int, default=65, help="Number of frames to generate (default: 65)")
    parser.add_argument("--output", default="wan-t2v.mp4", help="Output video file (default: wan-t2v.mp4)")
    parser.add_argument(
        "--profile-dir",
        default="./wan_profile",
        help="Base directory containing the saved profiles (default: ./wan_profile)",
    )
    args = parser.parse_args()

    transformer_profile_dir = f"{args.profile_dir}/transformer"
    transformer2_profile_dir = f"{args.profile_dir}/transformer2"

    pipe = WanPipeline.from_pretrained(MODEL_ID, torch_dtype=torch.bfloat16)

    for name, component in pipe.components.items():
        if isinstance(component, torch.nn.Module) and name not in ("transformer", "transformer_2"):
            component.to("cuda")

    offload_config = OffloadConfig(
        min_blocks=2,
        include_patterns=MODULE_PATTERNS,
    )

    pipe.transformer = flextensor.offload_from_profile(
        pipe.transformer,
        transformer_profile_dir,
        config=offload_config,
        name="transformer",
    )
    pipe.transformer_2 = flextensor.offload_from_profile(
        pipe.transformer_2,
        transformer2_profile_dir,
        config=offload_config,
        name="transformer2",
    )

    frames = pipe(
        prompt=args.prompt,
        negative_prompt=args.negative_prompt,
        num_frames=args.num_frames,
    ).frames[0]
    export_to_video(frames, args.output, fps=16)
    print(f"Video saved to {args.output}")

    flextensor.release("transformer")
    flextensor.release("transformer2")


if __name__ == "__main__":
    main()
